substitutions:
  device_name: work-office-rf
  api_encryption_key: !secret api_encryption_key
  ota_password: !secret ota_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ip: "192.168.253.71"
  wifi_subnet: !secret wifi_subnet
  wifi_gateway: !secret wifi_gateway
  dns_server: !secret dns_server
  wifi_fallback: !secret fallback_password
  
packages:
  common: 
    url: https://github.com/AevumDecessus/esphome-configs
    file: common/common.yaml
    refresh: 0s
  rfbridge:
    url: https://github.com/AevumDecessus/esphome-configs
    file: hardware/esp8266/sonoff/rf-bridger2.yaml
    refresh: 0s